#!/usr/bin/env python3
"""Regenerates openmct/brand/openmct-accent.css: Open MCT in the brand accent.

Usage: python3 scripts/openmct-accent.py   (after `npm ci` in openmct/)

Open MCT's themes are compiled stylesheets, so their key colour (the blue of
selections, tree icons, menus, toggles...) cannot be changed with a variable.
This copies every declaration that uses it, from both themes, into one
stylesheet that sets the brand tokens instead, scoped to the matching
data-theme so it wins over the original. Rerun it after upgrading Open MCT.
"""

import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent / 'openmct'
DIST = ROOT / 'node_modules' / 'openmct' / 'dist'
OUT = ROOT / 'brand' / 'openmct-accent.css'

# theme stylesheet -> (data-theme, {key colour literal: replacement})
THEMES = {
    'espressoTheme.css': ('dark', {
        '#03ace4': 'var(--sp-accent)',
        # Major buttons, checkboxes: a fill under white text.
        '#007fad': 'var(--sp-accent-strong)',
    }),
    'snowTheme.css': ('light', {
        '#09c': 'var(--sp-accent)',
        '#007fad': 'var(--sp-accent-strong)',
        '#99e6ff': 'var(--sp-accent-soft)',
    }),
}
# rgba() forms of the same key colours, alpha kept.
RGBA = {'dark': (3, 172, 228), 'light': (0, 153, 204)}


def rules(css):
    """(at-rule prelude or None, selector, body) for every plain rule."""
    stack = []
    for match in re.finditer(r'([^{}]*)\{|\}', css):
        if match.group(0) == '}':
            if stack:
                stack.pop()
            continue
        prelude = match.group(1).strip()
        stack.append(prelude)
        if prelude.startswith('@'):
            continue
        end = css.index('}', match.end())
        body = css[match.end():end]
        if '{' in body:
            continue
        outer = [p for p in stack[:-1] if p.startswith('@')]
        # Keyframes and the like hold no selectors to scope.
        if any(not p.startswith(('@media', '@supports')) for p in outer):
            continue
        yield (outer[-1] if outer else None), prelude, body


def split_selectors(selector):
    """Splits on top-level commas only (not those inside :not(...))."""
    parts, depth, current = [], 0, ''
    for char in selector:
        depth += char == '('
        depth -= char == ')'
        if char == ',' and depth == 0:
            parts.append(current)
            current = ''
        else:
            current += char
    return parts + [current]


def scope(selector, theme):
    prefix = f':root[data-theme="{theme}"]'
    scoped = []
    for part in split_selectors(selector):
        part = part.strip()
        # Selectors on <html> itself attach to the prefix rather than nest.
        if part.startswith('html'):
            scoped.append(prefix + part[4:])
        else:
            scoped.append(f'{prefix} {part}')
    return ',\n'.join(scoped)


def main():
    out = ['/* Generated by scripts/openmct-accent.py. Do not edit by hand. */\n']
    for sheet, (theme, literals) in THEMES.items():
        css = (DIST / sheet).read_text()
        r, g, b = RGBA[theme]
        rgba = re.compile(rf'rgba\({r},\s*{g},\s*{b},\s*([\d.]+)\)')
        out.append(f'\n/* {sheet} */\n')
        for media, selector, body in rules(css):
            keep = []
            for declaration in body.split(';'):
                new = rgba.sub(lambda m: f'color-mix(in oklch, var(--sp-accent) {float(m.group(1)) * 100:g}%, transparent)',
                               declaration)
                for literal, token in literals.items():
                    new = re.sub(re.escape(literal) + r'(?![0-9a-fA-F])', token, new)
                if new != declaration:
                    keep.append(new.strip())
            if not keep:
                continue
            rule = f'{scope(selector, theme)} {{ {"; ".join(keep)}; }}\n'
            out.append(f'{media} {{\n{rule}}}\n' if media else rule)
    OUT.write_text(''.join(out))
    print(f'Wrote {OUT}')


if __name__ == '__main__':
    main()
